" NOTE: run :checkhealth to see for any errors after installation of plugins
" in nvim

set encoding=utf8
set nocompatible              " be iMproved, required
filetype off                  " required

" mapping leader to , instead of \
let mapleader = ","

set syntax=off
set ft=text
set conceallevel=0
set backspace=2
set number
set expandtab
autocmd Filetype yml setlocal tabstop=2
set tabstop=2
set shiftwidth=2
set softtabstop=2
set smarttab
set clipboard+=unnamed
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
map <F7> mzgg=G`z

fun! <SID>StripTrailingWhitespaces()
  let l = line(".")
  let c = col(".")
  %s/\s\+$//e
  call cursor(l, c)
endfun
autocmd BufWritePre * :call <SID>StripTrailingWhitespaces()


" https://vi.stackexchange.com/q/202
:set mouse=a

set rtp+=~/.vim/bundle/Vundle.vim
set ignorecase
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

" completion engine + sources
Plugin 'hrsh7th/nvim-cmp'
Plugin 'hrsh7th/cmp-nvim-lsp'
Plugin 'L3MON4D3/LuaSnip'
Plugin 'saadparwaiz1/cmp_luasnip'

" auto pairs (replaces coc-pairs)
Plugin 'windwp/nvim-autopairs'

" for debugging, prereq for nvim-dap-go
Plugin 'mfussenegger/nvim-dap'
nmap <silent> <leader>tb :lua require'dap'.toggle_breakpoint()<CR>
nmap <silent> <leader>tc :lua require'dap'.continue()<CR>
nmap <silent> <leader>tt :lua require'dap'.terminate()<CR>

" for golang nvim dap extension
Plugin 'leoluz/nvim-dap-go'
nmap <silent> <leader>td :lua require('dap-go').debug_test()<CR>

" for out of box nvim-dap setup with it's UI
Plugin 'rcarriga/nvim-dap-ui'
Plugin 'nvim-neotest/nvim-nio'

" Shows indentline
Plugin 'Yggdroot/indentLine'

Plugin 'scrooloose/nerdtree'
"autocmd vimenter * NERDTree
" https://github.com/scrooloose/nerdtree/issues/928
let g:NERDTreeNodeDelimiter = "\u00a0"
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
nmap <silent> <C-q>        :NERDTreeToggle<CR>
vmap <silent> <C-q> <Esc>  :NERDTreeToggle<CR>
omap <silent> <C-q>        :NERDTreeToggle<CR>
imap <silent> <C-q> <Esc>  :NERDTreeToggle<CR>
cmap <silent> <C-q> <C-u>  :NERDTreeToggle<CR>

" shows the git status for files on nerdtree
" NOTE: Has been archived, find a replacement
Plugin 'Xuyuanp/nerdtree-git-plugin'

" Adds the airline at the bottom of the editor bar
Plugin 'vim-airline/vim-airline'
let g:airline_powerline_fonts = 1

Plugin 'flazz/vim-colorschemes'
syntax enable
if has('gui_running')
  set background=light
else
  set background=dark
endif
let g:solarized_termcolors= 256
let g:solarized_termtrans = 1
let g:solarized_degrade = 1
let g:solarized_bold = 1
let g:solarized_underline = 1
let g:solarized_italic = 1
let g:solarized_contrast = "normal"
let g:solarized_visibility= "normal"
"colorscheme molokai
"source ~/.vim/bundle/vim-colorschemes/colors/solarized.vim

" Jump to a file via ctrl + p in the directory (using fzf)
nnoremap <C-p> :Files<CR>

" Shows git changes on the file being edited
Plugin 'airblade/vim-gitgutter'

Plugin 'fatih/vim-go'
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1
let g:go_highlight_extra_types = 1
" running both vim-go and nvim-lspconfig with gopls. To avoid duplicates,
" disable vim-go's own fmt/imports/lsp since lspconfig handles them
" - nvim-lspconfig → LSP (completion, imports, diagnostics, hover)
" - vim-go → build/test/run/coverage/alternate
let g:go_fmt_autosave = 0
let g:go_imports_autosave = 0
let g:go_mod_fmt_autosave = 0
let g:go_gopls_enabled = 0
let g:go_code_completion_enabled = 0
let g:go_doc_keywordprg_enabled = 0
let g:go_def_mapping_enabled = 0
let g:go_fmt_fail_silently = 1

" saves the file when we call :GoBuild etc, which calles :make in turn
set autowrite

" helpers to jump to the errors in the tab when we run :GoBuild
map <C-n> :cnext<CR>
map <C-m> :cprevious<CR>
nnoremap <leader>a :cclose<CR>

" run :GoBuild or :GoTestCompile based on the go file
function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#test#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction
autocmd FileType go nmap <leader>b :<C-u>call <SID>build_go_files()<CR>

autocmd FileType go nmap <leader>r  <Plug>(go-run)
autocmd FileType go nmap <leader>R :GoRun<space>
autocmd FileType go nmap <leader>t  <Plug>(go-test)
autocmd FileType go nmap <Leader>c <Plug>(go-coverage-toggle)

" :GoAlternate commands to split test files in different views
autocmd Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
autocmd Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
autocmd Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
autocmd Filetype go command! -bang AT call go#alternate#Switch(<bang>0, 'tabe')

" Only show quickfix lists
let g:go_list_type = "quickfix"

" Used for struct splits for text
Plugin 'AndrewRadev/splitjoin.vim'

" Install treesitter for syntax highlighting and code folding
Plugin 'nvim-treesitter/nvim-treesitter'


" fzf file search in directory
Plugin 'junegunn/fzf' " this is a dep for fzf.vim from their repo
Plugin 'junegunn/fzf.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

lua << EOF
-- completion
local cmp = require('cmp')
local luasnip = require('luasnip')

cmp.setup({
  snippet = {
    expand = function(args)
      luasnip.lsp_expand(args.body)
    end,
  },
  mapping = cmp.mapping.preset.insert({
    ['<TAB>'] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      else
        fallback()
      end
    end, { 'i', 's' }),
    ['<S-TAB>'] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_prev_item()
      else
        fallback()
      end
    end, { 'i', 's' }),
    ['<CR>'] = cmp.mapping.confirm({ select = true }),
  }),
  sources = cmp.config.sources({
    { name = 'nvim_lsp' },
    { name = 'luasnip' },
  }),
})

-- autopairs
require('nvim-autopairs').setup()
local cmp_autopairs = require('nvim-autopairs.completion.cmp')
cmp.event:on('confirm_done', cmp_autopairs.on_confirm_done())

-- LSP (nvim 0.11 native API)
local capabilities = require('cmp_nvim_lsp').default_capabilities()

vim.api.nvim_create_autocmd('LspAttach', {
  callback = function(ev)
    local opts = { noremap = true, silent = true, buffer = ev.buf }
    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
    vim.keymap.set('n', 'gy', vim.lsp.buf.type_definition, opts)
    vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
    vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
    vim.keymap.set('n', 'K',  vim.lsp.buf.hover, opts)
  end,
})

vim.lsp.config('gopls', {
  cmd = { 'gopls' },
  filetypes = { 'go', 'gomod', 'gowork', 'gotmpl' },
  root_markers = { 'go.work', 'go.mod', '.git' },
  capabilities = capabilities,
})
vim.lsp.enable('gopls')

vim.lsp.config('nil_ls', {
  cmd = { 'nil' },
  filetypes = { 'nix' },
  root_markers = { 'flake.nix', '.git' },
  capabilities = capabilities,
  settings = {
    ['nil'] = {
      formatting = { command = { 'nixpkgs-fmt' } },
    },
  },
})
vim.lsp.enable('nil_ls')

-- format + organize imports on save for Go
vim.api.nvim_create_autocmd('BufWritePre', {
  pattern = '*.go',
  callback = function()
    vim.lsp.buf.format({ async = false })
    vim.lsp.buf.code_action({
      context = { only = { 'source.organizeImports' } },
      apply = true,
    })
  end,
})

-- highlight symbol under cursor
vim.api.nvim_create_autocmd('CursorHold', {
  callback = function() vim.lsp.buf.document_highlight() end,
})
vim.api.nvim_create_autocmd('CursorMoved', {
  callback = function() vim.lsp.buf.clear_references() end,
})

-- treesitter
require('nvim-treesitter.configs').setup {
  ensure_installed = { "go", "lua", "vim" },
  highlight = {
    enable = false,
  },
  indent = {
    enable = true,
  },
}

EOF

lua << EOF
-- treesitter folding (separate block so it registers even if cmp/lsp setup above fails)
vim.api.nvim_create_autocmd('FileType', {
  callback = function(ev)
    pcall(vim.treesitter.start, ev.buf)
    vim.opt_local.foldmethod = 'expr'
    vim.opt_local.foldexpr = 'v:lua.vim.treesitter.foldexpr()'
    vim.opt_local.foldlevel = 99
  end,
})
EOF
